
export const allUser = (req,res) =>{
    try{

    }
    catch(err){
        console.log("allUser error: ",err);
    }

}
export const oneUser = (req,res) =>{
    try{

    }
    catch(err){
        console.log("oneUser error: ",err);
    }
}
export const postUser = (req,res) =>{
    try{

    }
    catch(err){
        console.log("postUser error: ",err);
    }
}
export const updateUser = (req,res) =>{
    try{

    }
    catch(err){
        console.log("updateUser error: ",err);
    }
}
export const deleteUser = (req,res) =>{
    try{

    }
    catch(err){
        console.log("deleteUser error: ",err);
    }
}
